// Mocks generated by Mockito 5.0.12 from annotations
// in wikly/test/features/tasks/domain/task_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:wikly/features/tasks/domain/entities/task.dart' as _i3;
import 'package:wikly/features/tasks/domain/repositories_interfaces/i_task_repository.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ITaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockITaskRepository extends _i1.Mock implements _i2.ITaskRepository {
  MockITaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String create(_i3.Task? task) =>
      (super.noSuchMethod(Invocation.method(#create, [task]), returnValue: '')
          as String);
  @override
  void update(_i3.Task? task) =>
      super.noSuchMethod(Invocation.method(#update, [task]),
          returnValueForMissingStub: null);
  @override
  void delete(String? id) =>
      super.noSuchMethod(Invocation.method(#delete, [id]),
          returnValueForMissingStub: null);
  @override
  _i4.Stream<Map<String, dynamic>> getStream() =>
      (super.noSuchMethod(Invocation.method(#getStream, []),
              returnValue: Stream<Map<String, dynamic>>.empty())
          as _i4.Stream<Map<String, dynamic>>);
}
